### ISSUE TITLE
TestNG unable to find tests in classpath

### ISSUE THREAD

**Issue by aristeia** [LemonadeLabInc/android-testng#2]
Hi,
I've encountered an issue trying to run instrumentation tests that I've replicated on the instrumentation tests in your own repository. Although building the project is successful, the following runtime error occurs (in this example, when running the "AndroidComponentsTest" test):

org.testng.TestNGException: 
Cannot find class in classpath: de.lemona.android.testng.test.AndroidComponentsTest
	at org.testng.xml.XmlClass.loadClass(XmlClass.java:81)
	at org.testng.xml.XmlClass.init(XmlClass.java:73)
	at org.testng.xml.XmlClass.<init>(XmlClass.java:59)
	at org.testng.xml.TestNGContentHandler.startElement(TestNGContentHandler.java:544)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
...

I've tried fixing this issue by adding a testng.xml file specifying the test path, but it didnt solve the issue.

**Comment by aristeia** [comment]
It seems that the build process is placing the instrumentation tests into a separate classes folder than the rest of the classes for a particular build variant, and that my classpath is only set to look at the build variant's classes, e.g. for a build variant named "debug". the tests' class files are put in "/app/build/intermediates/classes/androidTest/debug" whereas my classpath is looking for them in  "/app/build/intermediates/classes/debug". Not sure if this is an IntelliJ, TestNG, or android-testng issue.

**Comment by aristeia** [comment]
The issue is that I was trying to use android studio's blind build process. Running the exact gradle tasks from android studio, however, works fine. Ive added this list of gradle tasks to the readme in a pull request.
